---


- name: Installing necessaty system tools
  apt: yum={{ item }} state=present install_recommends=no
  with_items:
    - python-pip
    - vim
  become: yes
  become_method: sudo
  tags:
    - common